name: public_art
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  path: ^1.8.1
  args: ^2.0.0
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_multipart: ^1.0.0
  shelf_web_socket: ^1.0.1
  shelf_virtual_directory: ^3.0.0
  jaguar_jwt: ^3.0.0
  drift: ^1.6.0
  hive: ^2.2.1
  uuid: ^3.0.6

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
  build_runner: ^2.1.10
  drift_dev: ^1.6.0
  hive_generator: ^1.1.3
